# SERVER
server.port=9306
server.servlet.contextPath=/api-sidep-parvulo

#DATASOURCE
api.sidep.datasource.driver-class-name=org.postgresql.Driver
api.sidep.datasource.url=jdbc:postgresql://192.168.32.40:5432/sidep
api.sidep.datasource.username=adm_sidep_prod
api.sidep.datasource.password=adm_sidep_prod

# LOGGING
logging.level.root = DEBUG
logging.level.cl.mineduc.parvuloapi = DEBUG
logging.level.com.zaxxer.hikari = DEBUG
logging.level.com.ibatis.common = DEBUG
logging.level.java.sql = DEBUG
logging.level.org.springframework.data.rest.webmvc= ERROR
logging.level.org.springframework.web.servlet.mvc= ERROR
logging.level.org.springframework.boot.actuate.endpoint.jmx=ERROR
logging.level.org.mongodb.driver=ERROR


