# SERVER
server.port=8080

# DATASOURCE
api.sidep.datasource.driver-class-name=org.postgresql.Driver
api.sidep.datasource.url=jdbc:postgresql://desarrollo-postgres.cd1ddzwdjjgq.us-east-1.rds.amazonaws.com:5432/bd_siped
api.sidep.datasource.username=postgres
api.sidep.datasource.password=Catena2015